apiVersion: v1
kind: Config
preferences: {}

clusters:
- name: my-cluster
  cluster:
    certificate-authority-data: <BASE64-ENCODED-CA-CERT-DATA>
    server: https://kubernetes-api-server.example.com

users:
- name: my-user
  user:
    client-certificate-data: <BASE64-ENCODED-CLIENT-CERT-DATA>
    client-key-data: <BASE64-ENCODED-CLIENT-KEY-DATA>

contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user

current-context: my-context
